// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteOS.Web.Database;

#nullable disable

namespace RemoteOS.Web.Migrations
{
    [DbContext(typeof(ROSContext))]
    [Migration("20220818112134_World_structure_update")]
    partial class World_structure_update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4");

            modelBuilder.Entity("RemoteOS.Web.Database.ComputerDBEntry", b =>
                {
                    b.Property<Guid>("Address")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Facing")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("X")
                        .HasColumnType("REAL");

                    b.Property<float?>("Y")
                        .HasColumnType("REAL");

                    b.Property<float?>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Address");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("RemoteOS.Web.Database.IBlock", b =>
                {
                    b.Property<int>("X")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("Z")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("X", "Y", "Z");

                    b.ToTable("World");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IBlock");
                });

            modelBuilder.Entity("RemoteOS.Web.Database.ScannedBlock", b =>
                {
                    b.HasBaseType("RemoteOS.Web.Database.IBlock");

                    b.Property<float>("Hardness")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("ScannedBlock");
                });

            modelBuilder.Entity("RemoteOS.Web.Database.AnalyzedBlock", b =>
                {
                    b.HasBaseType("RemoteOS.Web.Database.ScannedBlock");

                    b.Property<int>("Argb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HarvestLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HarvestTool")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Meta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Props")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("AnalyzedBlock");
                });
#pragma warning restore 612, 618
        }
    }
}
